development:
  adapter: postgresql
  database: epya_development
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost
  password: yourPass

test:
  adapter: postgresql
  database: epya_test
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost
  password: yourPass

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
