development:
  adapter: postgresql
  database: epya_development
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost

test:
  adapter: postgresql
  database: epya_test
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost

production:
  adapter: postgresql
  database: epya_production
  pool: 5
  timeout: 5000